add the FirebaseAuthService
yanpepik/BalancedDiet pull request #1
Opened 2022-03-24 15:42 UTC by yanpepik

2022-03-24 16:08 UTC, lzedm requested changes

2022-03-24 16:08 UTC, lzedm commented on BalancedDiet/Services/FirebaseAuthService.swift
> +                            break
completion(.failure(.unownError))

2022-03-24 16:08 UTC, lzedm commented on BalancedDiet/Services/FirebaseAuthService.swift
> +                        break
completion(.failure(.unownError))

2022-03-24 16:09 UTC, yanpepik commented on BalancedDiet/Services/FirebaseAuthService.swift
> +                if let errorCode = AuthErrorCode(rawValue: error.code) {
add [weak self] in closure

2022-03-24 19:41 UTC, yanpepik commented on BalancedDiet/Helpers/DataLocalization.strings
> +// MARK: - FirebaseAuth Error
add a new line

2022-03-24 19:43 UTC, yanpepik commented on BalancedDiet/Application/SceneDelegate.swift
> +//        guard let windowScene = (scene as? UIWindowScene) else { return }
remove commented lines

2022-03-24 19:44 UTC, yanpepik commented on BalancedDiet/Helpers/DataLocalization.strings
> +// MARK: - FirebaseAuth Error
remove extra text

2022-03-24 19:46 UTC, yanpepik commented on BalancedDiet/Services/FirebaseAuthService.swift
> +    func createUser(email: String, password: String, completion: @escaping (Result<FirebaseDTO.CreateUser, FirebaseError>) -> Void) {
pass the model as a parameter and fix error handling

2022-03-24 20:16 UTC, yanpepik commented on BalancedDiet/Services/FirebaseAuthService.swift
> +    func signOut(completion: @escaping (Result<Void, FirebaseError>) -> Void) {
исправил

2022-03-24 20:17 UTC, yanpepik commented on BalancedDiet/Services/FirebaseUserError.swift
> +
исправил

2022-03-24 20:17 UTC, yanpepik commented on BalancedDiet/Services/FirebaseAuthService.swift
> +    func createUser(email: String, password: String, completion: @escaping (Result<FirebaseDTO.CreateUser, FirebaseError>) -> Void) {
исправил

2022-03-24 20:17 UTC, yanpepik commented on BalancedDiet/Services/FirebaseAuthService.swift
> +                        break
исправил

2022-03-24 20:19 UTC, yanpepik commented on BalancedDiet/Services/FirebaseAuthService.swift
> +                        break
исправил

2022-03-25 08:55 UTC, yanpepik commented on BalancedDiet/Services/FirebaseAuthService.swift
> +                            break
исправил

2022-03-25 09:57 UTC, vodyan-nucleus requested changes

2022-03-25 09:57 UTC, vodyan-nucleus commented on BalancedDiet/Helpers/DataLocalization.strings
> +// MARK: - FirebaseAuth Error
не вижу изменений

2022-03-25 09:57 UTC, vodyan-nucleus commented on BalancedDiet/Services/FirebaseDTO.swift
> +
Убрать пустую строку

2022-03-25 09:57 UTC, vodyan-nucleus commented on BalancedDiet/Services/FirebaseDTO.swift
> +
убрать 3 путсые строки в конце

2022-03-25 09:57 UTC, vodyan-nucleus commented on BalancedDiet/Application/SceneDelegate.swift
> +        window = UIWindow(windowScene: windowScene)
почему это здесь?

2022-03-25 09:57 UTC, vodyan-nucleus commented on BalancedDiet/Application/SceneDelegate.swift
> -        // Use this method to optionally configure and attach the UIWindow `window` to the provided UIWindowScene `scene`.
должно быть тут

2022-03-25 09:57 UTC, vodyan-nucleus commented on BalancedDiet/Application/SceneDelegate.swift
> -        // Called as the scene is being released by the system.
убрать методы которые не используешь

2022-03-25 10:03 UTC, yanpepik commented on BalancedDiet/Services/FirebaseDTO.swift
> +
исправил

2022-03-25 10:13 UTC, vodyan-nucleus approved these changes

2022-03-25 10:14 UTC, merged