update commit
yanpepik/BalancedDiet pull request #6
Opened 2022-04-14 11:58 UTC by yanpepik

2022-04-14 12:46 UTC, vodyan-nucleus requested changes

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Resources/Assets.xcassets/clear-black-bordered.imageset/Contents.json
> +}
должно быть single scale (а не 2х 3х ...)

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Resources/Assets.xcassets/clear-black-bordered.imageset/Contents.json
> +}
и нажать галочку preserve vector data

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Resources/Assets.xcassets/clear-black.imageset/Contents.json
> +{
тоже самое что и в BalancedDiet/Resources/Assets.xcassets/clear-black-bordered.imageset/Contents.json

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Resources/Assets.xcassets/eye-closed.imageset/Contents.json
> +{
тоже самое что и в BalancedDiet/Resources/Assets.xcassets/clear-black-bordered.imageset/Contents.json

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Resources/Assets.xcassets/eye-opened.imageset/Contents.json
> +{
тоже самое что и в BalancedDiet/Resources/Assets.xcassets/clear-black-bordered.imageset/Contents.json

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Resources/Assets.xcassets/eye-slash.imageset/Contents.json
> +    {
тоже самое что и в BalancedDiet/Resources/Assets.xcassets/clear-black-bordered.imageset/Contents.json

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Resources/Assets.xcassets/eye.imageset/Contents.json
> +    {
тоже самое что и в BalancedDiet/Resources/Assets.xcassets/clear-black-bordered.imageset/Contents.json

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Resources/Assets.xcassets/info-circle.imageset/Contents.json
> +    {
тоже самое что и в BalancedDiet/Resources/Assets.xcassets/clear-black-bordered.imageset/Contents.json

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Resources/Extensions/String.swift
> +    enum ValidationCases: String {
Почему это тут?

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Resources/Extensions/String.swift
> +    func isValid(_ `case`: ValidationCases) -> Bool {
Почему это тут? Лучше сделать отдельный менеджер, который будет отвечать за валидацию.

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginInteractor.swift
> +    func getUser(request: Login.DisplayLogin.Request) {
Почему бизнесс логика в пул реквесте, который относится только к созданию UI?

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginLocalization.strings
> +"DoesentHaveAccount" = "Doesent have an account?";
Почему с большой буквы, если все остальное с маленькой?

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginModels.swift
> +        }
нужен пробел

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginModels.swift
> +        }
нужен пробел

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginModels.swift
> +        }
и скобки в одну строчку, если модели пустые

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginModels.swift
> +        }
пробел

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginModels.swift
> +        }
пробел

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginModels.swift
> +            var routeToSignUpButton: String?
routeToSignUpButtonTitle

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginModels.swift
> +            var routeToSignUpButton: String?
sceneNameLabelText
и тд

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginModels.swift
> +            var routeToSignUpButton: String?
почему все опциональное?

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginPresenter.swift
> +        viewController?.displayData(viewModel: viewModel)
displayInititalData

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginPresenter.swift
> +    func presetUser(response: Login.DisplayLogin.Response) {
убрать из этого pr

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginProtocols.swift
> +    func fetchData(request: Login.InitialData.Request)
fetchInitialData

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginProtocols.swift
> +    func displayData(viewModel: Login.InitialData.ViewModel)
displayInitialData

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginProtocols.swift
> +    func presentData(response: Login.InitialData.Response)
presentInitialData

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginProtocols.swift
> +    func back()
back используется?

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginViewController.swift
> +    private let sceneNameLabel: TextLabel = {
private let sceneNameLabel = TextLabel()

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginViewController.swift
> +        let button = Button()
зачем кложур?

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginViewController.swift
> +        let button = Button()
зачем кложур?

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginViewController.swift
> +            $0.leading.equalTo(containerView.snp.leading).inset(view.frame.width / 16)
вынести числа в константы

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/SignUp/SignUpInteractor.swift
> +    enum Endpoint: FirestoreEndpointProtocol {
и почему бизнесс логика в этом пре, убери

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/SignUp/SignUpInteractor.swift
> +    func createUser(request: Login.DisplayLogin.Request) {
и почему бизнесс логика в этом пре, убери

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/SignUp/SignUpModels.swift
> +    enum DisplaySignUp {
и почему бизнесс логика в этом пре, убери

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/SignUp/SignUpPresenter.swift
> +    func presetUser(response: SignUp.DisplaySignUp.Response) {
и почему бизнесс логика в этом пре, убери

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/SignUp/SignUpRouter.swift
> +
добавить марку

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/SignUp/SignUpViewController.swift
> +        label.text = R.string.signUpLocalization.signup()
нужно прокинуть данные по циклу (InitialData)

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/SignUp/SignUpViewController.swift
> +        button.addTarget(self, action: #selector(routeToLoginPressed), for: .touchUpInside)
вынести таргеты в отдельный метод

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/SignUp/SignUpViewController.swift
> +    private func registerForKeybordNotifications() {
почему она здесь? должна быть ниже

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/SignUp/SignUpViewController.swift
> +        registerForKeybordNotifications()
почему это в методе, который отвечает за добавление сабвью?

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/SignUp/SignUpViewController.swift
> +    private func setupLayout() {
вынести все числа в константы

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/UIElemets/Button/Button.swift
> +    // MARK: - Override Methods
это не метод, а свойство

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/UIElemets/Shadow/Shadow.swift
> +enum Shadow {
название не очень

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/UIElemets/Shadow/Shadow.swift
> +import Foundation
зачем Foundation?

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/UIElemets/TextLabel/TextLabel.swift
> +import Foundation
зачем Foundation?

2022-04-14 12:46 UTC, vodyan-nucleus commented on BalancedDiet/UIElemets/TextLabel/TextLabel.swift
> +class TextLabel: UILabel {
Зачем этот класс вообще?

2022-04-14 16:57 UTC, vodyan-nucleus requested changes

2022-04-14 16:57 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginProtocols.swift
> +import Foundation
зачем Foundation?

2022-04-14 16:57 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginRouter.swift
> +    // MARK: -LoginRoutingLogic
// MARK: - LoginRoutingLogic пропустил пробел

2022-04-14 16:57 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginViewController.swift
> +    private lazy var loginWithGoogleButton = Button()
Зачем Lazy?

2022-04-14 16:57 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginViewController.swift
> +    private lazy var loginWithFacebookButton = Button()
Зачем Lazy?

2022-04-14 16:57 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginViewController.swift
> +    private lazy var loginButton = Button()
Зачем Lazy?

2022-04-14 16:57 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginViewController.swift
> +    private lazy var routeToSignUpButton: UIButton = {
Зачем Lazy?

2022-04-14 16:57 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginViewController.swift
> +        configureView()
лучше добавить сюда вызов метода startSettings()

2022-04-14 16:57 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginViewController.swift
> +        fetchInitialData()
и вынести fetchInitialData() в startSettings()

2022-04-14 16:57 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginViewController.swift
> +        forgotPasswordButton.addTarget(
это должно поместится в одну строку

2022-04-14 16:57 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/SignUp/SignUpInteractor.swift
> +
лишний пробел

2022-04-14 16:57 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/SignUp/SignUpProtocols.swift
> +import UIKit
зачем UIkit?

2022-04-14 16:57 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/SignUp/SignUpViewController.swift
> +    private lazy var signUpButton = Button()
зачем Lazy?

2022-04-14 16:57 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/SignUp/SignUpViewController.swift
> +    private func registerForKeybordNotifications() {
почему не исправил?

2022-04-14 16:57 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/SignUp/SignUpViewController.swift
> +        signUpButton.addTarget(
помещается в одну строку

2022-04-14 16:57 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/SignUp/SignUpViewController.swift
> +    private func configureView() {
должно быть вверху

2022-04-14 16:57 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/SignUp/SignUpViewController.swift
> +    private func setupSubviews() {
должно быть вверху

2022-04-14 16:57 UTC, vodyan-nucleus commented on BalancedDiet/ValodationManager/ExtensionString.swift
> +    enum ValidationCases: String {
Почему не убрал валидацию?

2022-04-14 16:57 UTC, vodyan-nucleus commented on BalancedDiet/ValodationManager/ExtensionString.swift
> +    func isValid(_ `case`: ValidationCases) -> Bool {
Почему не убрал валидацию?

2022-04-15 09:47 UTC, vodyan-nucleus requested changes

2022-04-15 09:47 UTC, vodyan-nucleus commented on BalancedDiet/UIElemets/Line/LineView.swift
> +        static let lineheight: CGFloat = 2
lineHeight

2022-04-15 14:31 UTC, lzedm commented on BalancedDiet/Resources/Extensions/UIViewController.swift
> +extension UIViewController {
пробел

2022-04-15 14:54 UTC, lzedm requested changes

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/Resources/Extensions/UIViewController.swift
> +extension UIViewController {
Пробел

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/Scenes/LogIn/LoginInteractor.swift
> +// MARK: - LogInBusinessLogic
LoginBusinessLogic

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/Scenes/LogIn/LoginPresenter.swift
> +//  LogInPresenter.swift
LoginPresenter

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/Scenes/LogIn/LoginPresenter.swift
> +// MARK: - LogInPresentationLogic
LoginPresentationLogic

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/Scenes/LogIn/LoginRouter.swift
> +//  LogInRouter.swift
LoginRouter

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/Scenes/LogIn/LoginViewController.swift
> +        static let multiplyer: CGFloat = 0.01
multiplier

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/Scenes/LogIn/LoginViewController.swift
> +        fatalError("init(coder:) has not been implemented in LogInViewController")
LoginViewController

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/Scenes/LogIn/LoginViewController.swift
> +        guard let userInfo = (notification as Notification).userInfo else { return }
guard 
       let userInfo = (notification as Notification).userInfo,
       let keyboardNSValue = userInfo[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue
else { return }

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/Scenes/LogIn/LoginViewController.swift
> +        scrollView.contentInset.bottom = .zero
scrollView?

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/Scenes/LogIn/LoginViewController.swift
> +        scrollView.contentInset.bottom = keyboardFrame.size.height
scrollView?

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/Scenes/LogIn/LoginViewController.swift
> +// MARK: - LogInDisplayLogic
LoginDisplayLogic

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/Scenes/SignUp/SignUpModels.swift
> +
SwiftLint захотел?

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/Scenes/SignUp/SignupRouter.swift
> +
//MARK: - ???

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/Scenes/SignUp/SignupViewController.swift
> +        static let multiplyer: CGFloat = 0.01
multiplier

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/Scenes/SignUp/SignupViewController.swift
> +    private lazy var haveAccountStackView:  UIStackView = {
Пробел

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/Scenes/SignUp/SignupViewController.swift
> +
Ещё пробел

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/Scenes/SignUp/SignupViewController.swift
> +        guard let userInfo = (notification as Notification).userInfo else { return }
guard 
let userInfo = (notification as Notification).userInfo,
let keyboardNSValue = userInfo[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue
else { return }

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/UIElemets/Line/LineView.swift
> +        static let lineheight: CGFloat = 2
Не исправил

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/UIElemets/Line/LineView.swift
> +
Пробел

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/UIElemets/Line/LineView.swift
> +    required init?(coder aDecoder: NSCoder) {
Пробел

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/UIElemets/Line/LineView.swift
> +            $0.leading.equalToSuperview()
$0.leading.centerY.equalToSuperview()

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/UIElemets/Line/LineView.swift
> +            $0.trailing.equalToSuperview()
$0.trailing.centerY.equalToSuperview()

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/UIElemets/Line/LineView.swift
> +            $0.top.bottom.equalToSuperview()
$0.top.bottom.center.equalToSuperview()

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/UIElemets/TextField/TextField.swift
> +        fatalError("init(coder:) has not been implemented in CustomTextField")
CustomTextField???

2022-04-15 14:54 UTC, lzedm commented on BalancedDiet/UIElemets/TextField/TextFieldView.swift
> +        fatalError("init(coder:) has not been implemented in CustomTextField")
CustomTextField???

2022-04-15 17:34 UTC, merged